language: "en_EN"
custom_command: "cape"
storage_mode: "file"
#storage_mode: "database"
# database: "mysql" # mysql, postgresql, sqlite
# host: "localhost"
# port: "3306"
# database_name: "prodigy_cape"
# username: "root"
# password: "root"

#database: "mongodb"
# uri: "mongodb://localhost:27017"

